CREATE TABLE Sales_Data AS
SELECT * FROM Sales_Canada
UNION ALL
SELECT * FROM Sales_China
UNION ALL
SELECT * FROM Sales_India
UNION ALL
SELECT * FROM Sales_Nigeria
UNION ALL
SELECT * FROM Sales_UK
UNION ALL
SELECT * FROM Sales_US;
